from __future__ import annotations

import argparse
import binascii
import hashlib
import json
import struct
import zlib
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEMO = REPO / "demo"
SCENARIOS = DEMO / "scenarios"
GENERATOR_VERSION = "1.1.0"


@dataclass(frozen=True)
class ScenarioSpec:
    scenario_id: str
    title: str
    description: str
    files: dict[str, bytes]


def png_chunk(kind: bytes, payload: bytes) -> bytes:
    checksum = binascii.crc32(kind + payload) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + kind + payload + struct.pack(">I", checksum)


def texture_png(asset: str, channel: str, udim: int, size: int = 128) -> bytes:
    seed = int.from_bytes(hashlib.sha256(f"{asset}:{channel}:{udim}".encode()).digest()[:4])
    rows = bytearray()
    for y in range(size):
        rows.append(0)
        for x in range(size):
            checker = ((x // 16) + (y // 16)) % 2
            if channel == "N":
                red = 112 + ((x + seed) % 32)
                green = 112 + ((y + seed // 7) % 32)
                blue = 245
            elif channel == "R":
                value = 45 + ((x * 2 + y + seed) % 180)
                red = green = blue = value
            else:
                red = (seed + x * 3 + checker * 55) % 256
                green = (seed // 3 + y * 2 + checker * 35) % 256
                blue = (seed // 11 + x + y + checker * 20) % 256
            rows.extend((red, green, blue))
    header = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + png_chunk(b"IHDR", header)
        + png_chunk(b"IDAT", zlib.compress(bytes(rows), level=9))
        + png_chunk(b"IEND", b"")
    )


def ascii_fbx(asset: str, version: int) -> bytes:
    identifier = int.from_bytes(hashlib.sha256(f"{asset}:{version}".encode()).digest()[:7], "big")
    text = f"""; FBX 7.4.0 project file
; Synthetic redistributable demo mesh generated by Asset Delivery Organizer.
FBXHeaderExtension:  {{
    FBXHeaderVersion: 1003
    FBXVersion: 7400
}}
Objects:  {{
    Geometry: {identifier}, \"Geometry::{asset}\", \"Mesh\" {{
        Vertices: *24 {{
            a: -50,-50,0,50,-50,0,50,50,0,-50,50,0,-50,-50,100,50,-50,100,50,50,100,-50,50,100
        }}
        PolygonVertexIndex: *24 {{
            a: 0,1,2,-4,4,7,6,-6,0,4,5,-2,1,5,6,-3,2,6,7,-4,4,0,3,-8
        }}
    }}
    Model: {identifier + 1}, \"Model::{asset}\", \"Mesh\" {{
        Version: {version}
    }}
}}
Connections:  {{
    C: \"OO\",{identifier},{identifier + 1}
}}
"""
    return text.encode("utf-8")


def ascii_usd(asset: str, version: int) -> bytes:
    return f"""#usda 1.0
(
    customLayerData = {{ string generator = \"asset-delivery-organizer-demo\" }}
)
def Xform \"{asset}\" {{
    custom int deliveryVersion = {version}
    def Mesh \"PreviewMesh\" {{
        int[] faceVertexCounts = [3]
        int[] faceVertexIndices = [0, 1, 2]
        point3f[] points = [(0, 0, 0), (100, 0, 0), (0, 100, 0)]
    }}
}}
""".encode()


def add_texture_set(
    files: dict[str, bytes],
    asset: str,
    *,
    directory: str = "Textures",
    udims: tuple[int, ...] = (1001,),
    channels: tuple[str, ...] = ("B", "N", "R"),
) -> None:
    for udim in udims:
        for channel in channels:
            files[f"{directory}/T_{asset}_{channel}.{udim}.png"] = texture_png(asset, channel, udim)


def clean_environment() -> ScenarioSpec:
    files: dict[str, bytes] = {
        "Meshes/SM_TempleGate_v003.fbx": ascii_fbx("TempleGate", 3),
        "Meshes/SM_CourtyardRock_v004.fbx": ascii_fbx("CourtyardRock", 4),
        "Meshes/SM_StoneLantern_v002.fbx": ascii_fbx("StoneLantern", 2),
        "Documentation/supplier_manifest.txt": b"Supplier: Northwind Art\nBatch: ENV-042\nStatus: review\n",
    }
    add_texture_set(files, "TempleGate", udims=(1001, 1002))
    add_texture_set(files, "CourtyardRock")
    add_texture_set(files, "StoneLantern")
    return ScenarioSpec(
        "01_clean_environment_delivery",
        "合规环境资产交付",
        "三件环境资产，其中 TempleGate 使用两个完整 UDIM；预期零问题。",
        files,
    )


def faulty_supplier_drop() -> ScenarioSpec:
    files: dict[str, bytes] = {
        "Meshes/temple-gate-final.fbx": ascii_fbx("TempleGateBadName", 9),
        "Meshes/SM_TempleGate_v001.fbx": ascii_fbx("TempleGate", 1),
        "Meshes/SM_TempleGate_v002.fbx": ascii_fbx("TempleGate", 2),
        "Meshes/SM_TempleGate_v003.fbx": ascii_fbx("TempleGate", 3),
        "Meshes/SM_BrokenStatue_v004.fbx": ascii_fbx("BrokenStatue", 4),
        "Documentation/vendor_notes.txt": b"Please use final mesh. Normal maps will follow later.\n",
    }
    add_texture_set(files, "TempleGate", channels=("B",))
    add_texture_set(files, "BrokenStatue", channels=("B", "N"))
    add_texture_set(files, "BrokenStatue", udims=(1002,))
    return ScenarioSpec(
        "02_supplier_drop_with_issues",
        "典型供应商问题包",
        "包含错误命名、两个旧版本，以及两组缺失贴图通道；适合演示问题证据。",
        files,
    )


def multi_asset_udim_batch() -> ScenarioSpec:
    assets = (
        "AncientWall",
        "Archway",
        "CliffLarge",
        "GroundTile",
        "MarketStall",
        "RoofModule",
        "ShrineBase",
        "WoodBridge",
    )
    files: dict[str, bytes] = {
        "Documentation/batch.csv": (
            "asset,department,reviewer\n"
            + "\n".join(f"{asset},environment,ta_review" for asset in assets)
            + "\n"
        ).encode(),
        "Documentation/README.txt": b"Synthetic 8-asset, 2-UDIM review batch.\n",
    }
    for index, asset in enumerate(assets, start=1):
        files[f"Meshes/SM_{asset}_v{index + 2:03d}.usd"] = ascii_usd(asset, index + 2)
        add_texture_set(files, asset, udims=(1001, 1002))
    return ScenarioSpec(
        "03_multi_asset_udim_batch",
        "多资产多 UDIM 批量交付",
        "八件资产、每件两个完整 UDIM，用于展示递归扫描规模、稳定事实和吞吐。",
        files,
    )


def nested_vendor_batch() -> ScenarioSpec:
    files: dict[str, bytes] = {
        "Vendor_A/Environment/Meshes/SM_Cliff_v006.fbx": ascii_fbx("Cliff", 6),
        "Vendor_A/Environment/Meshes/SM_Cliff_v007.fbx": ascii_fbx("Cliff", 7),
        "Vendor_A/Environment/Documentation/review.txt": b"Vendor A revision 7 supersedes revision 6.\n",
        "Vendor_B/Props/Meshes/crate_export.fbx": ascii_fbx("CrateBadName", 1),
        "Vendor_B/Props/Meshes/SM_Crate_v002.fbx": ascii_fbx("Crate", 2),
        "Vendor_B/Props/Documentation/review.txt": b"Crate roughness is pending.\n",
    }
    add_texture_set(files, "Cliff", directory="Vendor_A/Environment/Textures")
    add_texture_set(
        files,
        "Crate",
        directory="Vendor_B/Props/Textures",
        channels=("B", "N"),
    )
    add_texture_set(files, "Barrel", directory="Vendor_B/Props/Textures")
    return ScenarioSpec(
        "04_nested_multi_vendor_batch",
        "嵌套多供应商交付",
        "两个供应商、不同资产层级，包含旧 Cliff、错误 Crate 命名和缺失粗糙度。",
        files,
    )


def delivery_boundary_preflight() -> ScenarioSpec:
    files: dict[str, bytes] = {
        "Meshes/SM_Watchtower_v005.fbx": ascii_fbx("Watchtower", 5),
        "Meshes/SM_Watchtower_v005.blend": b"BLENDER-v300 synthetic source placeholder\n",
        "Textures/T_Watchtower_source.psd": b"8BPS synthetic layered-source placeholder\n",
        "Exports/SM_Watchtower_v004.fbx": ascii_fbx("WatchtowerExport", 4),
        "Temp/watchtower-preview.png": texture_png("WatchtowerPreview", "B", 1001),
        "Documentation/vendor_brief.docx": b"Synthetic vendor brief; ignored by format policy.\n",
    }
    add_texture_set(files, "Watchtower")
    return ScenarioSpec(
        "05_delivery_boundary_preflight",
        "供应商交付边界预检",
        "包含两处错误目录、Blender/PSD 源文件格式，以及允许忽略的 Documentation 文档。",
        files,
    )


def scenario_specs() -> list[ScenarioSpec]:
    return [
        clean_environment(),
        faulty_supplier_drop(),
        multi_asset_udim_batch(),
        nested_vendor_batch(),
        delivery_boundary_preflight(),
    ]


def manifest(specs: list[ScenarioSpec]) -> dict[str, object]:
    scenarios = []
    for spec in specs:
        facts = [
            {
                "relative_path": path,
                "size_bytes": len(payload),
                "sha256": hashlib.sha256(payload).hexdigest(),
            }
            for path, payload in sorted(spec.files.items())
        ]
        scenarios.append(
            {
                "scenario_id": spec.scenario_id,
                "title": spec.title,
                "description": spec.description,
                "file_count": len(facts),
                "total_bytes": sum(item["size_bytes"] for item in facts),
                "files": facts,
            }
        )
    return {
        "schema_id": "asset-delivery-organizer-demo-assets/1",
        "generator_version": GENERATOR_VERSION,
        "license": "CC0-1.0 synthetic fixtures",
        "scenarios": scenarios,
    }


def serialized(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def expected_paths(specs: list[ScenarioSpec]) -> set[Path]:
    return {SCENARIOS / spec.scenario_id / relative for spec in specs for relative in spec.files}


def assert_generated_root() -> None:
    resolved = SCENARIOS.resolve(strict=False)
    expected = (REPO / "demo" / "scenarios").resolve(strict=False)
    if resolved != expected or REPO not in resolved.parents:
        raise RuntimeError(f"refusing to modify unexpected demo root: {resolved}")


def write_assets(specs: list[ScenarioSpec]) -> None:
    assert_generated_root()
    expected = expected_paths(specs)
    SCENARIOS.mkdir(parents=True, exist_ok=True)
    for spec in specs:
        root = SCENARIOS / spec.scenario_id
        for relative, payload in spec.files.items():
            target = root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(payload)
    for path in sorted(SCENARIOS.rglob("*"), reverse=True):
        if path.is_file() and path not in expected:
            path.unlink()
        elif path.is_dir() and not any(path.iterdir()):
            path.rmdir()
    (DEMO / "assets-manifest.json").write_text(
        serialized(manifest(specs)), encoding="utf-8", newline="\n"
    )


def check_assets(specs: list[ScenarioSpec]) -> list[str]:
    errors: list[str] = []
    expected = expected_paths(specs)
    actual = (
        {path for path in SCENARIOS.rglob("*") if path.is_file()} if SCENARIOS.exists() else set()
    )
    for missing in sorted(expected - actual):
        errors.append(f"missing: {missing.relative_to(DEMO).as_posix()}")
    for extra in sorted(actual - expected):
        errors.append(f"unexpected: {extra.relative_to(DEMO).as_posix()}")
    for spec in specs:
        for relative, payload in spec.files.items():
            path = SCENARIOS / spec.scenario_id / relative
            if path.is_file() and path.read_bytes() != payload:
                errors.append(f"content drift: {path.relative_to(DEMO).as_posix()}")
    manifest_path = DEMO / "assets-manifest.json"
    if not manifest_path.is_file() or manifest_path.read_text(encoding="utf-8") != serialized(
        manifest(specs)
    ):
        errors.append("assets-manifest.json is missing or stale")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate deterministic synthetic demo deliveries."
    )
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="Regenerate demo scenarios in place.")
    action.add_argument("--check", action="store_true", help="Fail if demo assets drifted.")
    args = parser.parse_args()
    specs = scenario_specs()
    if args.write:
        write_assets(specs)
        print(f"generated {sum(len(item.files) for item in specs)} files in {len(specs)} scenarios")
        return 0
    errors = check_assets(specs)
    if errors:
        print("demo asset verification failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"verified {sum(len(item.files) for item in specs)} files in {len(specs)} scenarios")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
